name: ESMS ID Scanner
description: ESMS ID Scanner for Desk Registration pickup
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.3.0
  http: ^0.13.4

dev_dependencies:
  flutter_mrz_scanner:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true